export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const ADD_POST_REQUEST = "POST_REQUEST";
export const ADD_POST_SUCCESS = "POST_SUCCESS";
export const ADD_POST_FAILURE = "POST_FAILURE";

export const ADD_COMMENT_REQUEST = "COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "COMMENT_FAILURE";
